version: '3.8'

services:
  mysql:
    image: mysql:9.0.0
    restart: "no"
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: WebSitePassword
      MYSQL_USER: WebSiteUser
      MYSQL_PASSWORD: WebSitePassword
      MYSQL_DATABASE: WebSite
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-pWebSitePassword"]
      interval: 10s
      timeout: 5s
      start_period: 10s
      retries: 5
    networks:
      - app-network

  web-site:
    image: web-site:latest
    build:
      context: .
      args:
        DOCKER_BUILDKIT: 1
    restart: "no"
    ports:
      - "8080:8080"
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/WebSite?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: WebSiteUser
      SPRING_DATASOURCE_PASSWORD: WebSitePassword
    networks:
      - app-network

volumes:
  mysql_data:

networks:
  app-network:
    driver: bridge
