package org.example.website.model;

public enum ProductCategory {

    KOVANVOROTA,
    KOVANKALITKA,
    KOVANZABOR,
    KOVANPERILA,
    KOVANREHOTKA,
    KOVANBESEDKA,
    KOVANKAHELI,
    KOVANMOSTI,
    KOVANMONGALI,
    KOVAMSKAMEIKI,
    URBAN,
    CHYGUNSKAMEYKI,
    SADOVIESTOLI,
    KOVANNABORI,
    LOFT,
    YLICHNIEYRNI,
    KONTEYNERITBO,
    FONARNIESTILBI,
    KOVANMEBEL,
    KOVANOGRAGDENIA,
    RITUALNIAIZDELIA,
    KOVANKOZIREKINAVES,
    ILEMENTKOVKI,
    TABLICKANADOM,
    OGRAGDENIEPLOSHADOK,
    RAZNIAKOVANIZDELIA,
    POLOMERNAIKRASKA,
    REZINIVAIKROHKA,
    XITPRODAG
}
